# Generated by Django 3.2.1 on 2021-06-09 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210609_0331"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(db_column="IsApproved", default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                db_column="RoleId",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_role",
                to="users.role",
            ),
        ),
        migrations.AddField(
            model_name="useroperator",
            name="is_active",
            field=models.BooleanField(
                db_column="IsActive",
                default=False,
                help_text="Is Student Activated or not",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(db_column="IsActive", default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(db_column="IsStaff", default=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table="Users",
        ),
    ]
