# Generated by Django 3.2.3 on 2021-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(db_column='NewsType', max_length=255)),
                ('title', models.TextField(db_column='Title')),
                ('description', models.TextField(db_column='Description')),
                ('body', models.TextField(db_column='Body')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'News',
            },
        ),
    ]
