# Generated by Django 3.2.1 on 2021-07-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('title_code', models.SlugField(default='', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'InterestIn',
            },
        ),
        migrations.CreateModel(
            name='IWouldLikeTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('title_code', models.SlugField(default='', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'IWouldLikeTo',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('title_code', models.SlugField(default='', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Specialty',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, db_column='Notes', default='', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', default='', max_length=255, null=True)),
                ('surname', models.CharField(blank=True, db_column='SurName', default='', max_length=255, null=True)),
                ('name_of_hospital', models.CharField(blank=True, db_column='NameOfHospital', default='', max_length=255, null=True)),
                ('email', models.EmailField(db_column='Email', help_text='Email Field', max_length=254)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('country', models.CharField(db_column='Country', max_length=255)),
                ('comment', models.TextField(blank=True, db_column='Comment', default='', null=True)),
                ('i_would_like_to', models.ForeignKey(db_column='IWouldLikeToID', on_delete=django.db.models.deletion.CASCADE, related_name='i_would_like_to_contact', to='contact.iwouldliketo')),
                ('interest_in', models.ForeignKey(db_column='InterestInID', on_delete=django.db.models.deletion.CASCADE, related_name='interest_in_contact', to='contact.interestin')),
                ('specialty', models.ForeignKey(db_column='SpecialtyID', on_delete=django.db.models.deletion.CASCADE, related_name='specialty_id', to='contact.specialty')),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
