# Generated by Django 3.2.3 on 2021-05-31 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(db_column="Country", max_length=255)),
                (
                    "applicant_organization",
                    models.CharField(
                        db_column="ApplicantOrganizationName", max_length=255
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_column="NameInLocalLanguage",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "applicant_organization_address",
                    models.TextField(db_column="ApplicantOrganizationAddress"),
                ),
                (
                    "organization_type",
                    models.CharField(db_column="OrganizationType", max_length=255),
                ),
                (
                    "organization_tax_id",
                    models.CharField(
                        blank=True,
                        db_column="OrganizationTaxId",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.TextField(blank=True, db_column="Website", null=True),
                ),
                (
                    "w9_form",
                    models.FileField(
                        blank=True, db_column="W-9Form", null=True, upload_to="uploads/"
                    ),
                ),
                (
                    "type_of_request",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Educational Grant"),
                            (2, "Research Grant"),
                            (3, "Third party educational events"),
                            (4, "Charitable Donation"),
                        ],
                        db_column="ResearchGrant",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Donation",
            },
        ),
        migrations.CreateModel(
            name="HowCanWeHelpYou",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="Title", max_length=255)),
                (
                    "name_code",
                    models.SlugField(default="", max_length=255, unique=True),
                ),
            ],
            options={
                "db_table": "HowCanWeHelpYou",
            },
        ),
        migrations.CreateModel(
            name="IAm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_column="Title", max_length=255)),
                (
                    "title_code",
                    models.SlugField(default="", max_length=255, unique=True),
                ),
            ],
            options={
                "db_table": "IAm",
            },
        ),
        migrations.CreateModel(
            name="EmailSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(db_column="FirstName", max_length=255)),
                ("last_name", models.CharField(db_column="LastName", max_length=255)),
                (
                    "city",
                    models.CharField(
                        blank=True, db_column="City", max_length=255, null=True
                    ),
                ),
                ("country", models.CharField(db_column="Country", max_length=255)),
                ("message", models.TextField(db_column="Message", default="")),
                (
                    "email",
                    models.EmailField(
                        db_column="Email", help_text="Email Field", max_length=254
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, db_column="State", max_length=255, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, db_column="PhoneNumber", max_length=255, null=True
                    ),
                ),
                (
                    "how_can_we_help",
                    models.ForeignKey(
                        db_column="HowCanWeHelpYouId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_support_how_can_we_help",
                        to="support.howcanwehelpyou",
                    ),
                ),
                (
                    "i_am",
                    models.ForeignKey(
                        db_column="IAmId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="i_am_support",
                        to="support.iam",
                    ),
                ),
            ],
            options={
                "db_table": "EmailSupport",
            },
        ),
    ]
