# Generated by Django 3.2.1 on 2021-06-07 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_emailsupport_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(db_column='Email', default=datetime.datetime(2021, 6, 7, 13, 32, 55, 226871, tzinfo=utc), help_text='Email Field', max_length=254),
            preserve_default=False,
        ),
    ]
