# Generated by Django 3.2.3 on 2021-05-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='FirstName', max_length=255)),
                ('message', models.TextField(blank=True, db_column='Notes', null=True)),
                ('email', models.EmailField(db_column='Email', help_text='Email Field', max_length=254)),
                ('cv', models.FileField(db_column='Resume', upload_to='uploads/')),
            ],
            options={
                'db_table': 'EmailData',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(db_column='JobTitle', max_length=255)),
                ('location', models.TextField(db_column='Location')),
                ('description', models.TextField(db_column='Description')),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now=True, db_column='CreationDate')),
            ],
            options={
                'db_table': 'JobPosting',
            },
        ),
        migrations.CreateModel(
            name='CandidateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='FirstName', max_length=255)),
                ('last_name', models.CharField(db_column='LastName', max_length=255)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('email', models.EmailField(db_column='Email', help_text='Email Field', max_length=254)),
                ('applying_date', models.DateField(auto_now=True, db_column='ApplyingDate')),
                ('resume', models.FileField(blank=True, db_column='Resume', null=True, upload_to='uploads/')),
                ('job', models.ForeignKey(db_column='JobId', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job', to='career.jobposting')),
            ],
            options={
                'db_table': 'CandidateDetail',
            },
        ),
    ]
