# Generated by Django 3.2.1 on 2021-06-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
