# Generated by Django 3.2.1 on 2021-06-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0002_jobposting_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatedetail",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
