# Generated by Django 3.2.1 on 2021-06-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_candidatedetail_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetail',
            name='new_file',
            field=models.FileField(blank=True, db_column='NewFile', null=True, upload_to='uploads/'),
        ),
    ]
